### ISSUE TITLE
Socket not found

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.wemo#1]
I have one Wemo-socket, no sensors. If I try to add the socket the popup window stays empty (still search I guess) and no errors in the console...

**Comment by freekwebdesign** [comment]
@bvdbos thanks for reporting this issue.
I will look into that the coming days, and will report back if I have found a solution.

**Comment by bvdbos** [comment]
Oeps, this works as it should. Wemo is a wifi-switch so it has to be connected to your wifi network first...
