### ISSUE TITLE
Allow cumulative monitoring (like z-wave devices)

### ISSUE THREAD

**Issue by Swiftnesses** [athombv/com.wemo#10]
I'd like to record the cumulative consumption of my devices, and track the data via insights (use tags in flows). It would be good to have this option and some cards, for example to reset readings. This is the same as is available on a number of z-wave energy monitoring devices in Homey.

**Comment by Swiftnesses** [comment]
@jeroenvollenbrock @BasKiers any chance of news cards for the insight plug, monitoring / resetting energy usage would be really awesome!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2599
