### ISSUE TITLE
No data on insights plug

### ISSUE THREAD

**Issue by Swiftnesses** [athombv/com.wemo#11]
Fresh install. No data is reported for an insights device.
<img width="437" alt="screen shot 2017-07-23 at 19 10 40" src="https://user-images.githubusercontent.com/1001877/28501756-aaaaef28-6fda-11e7-97f3-ca2c82d95956.png">

**Comment by MatthewWaanders** [comment]
Hey @Swiftnesses, 

I'm in the process of doing some work on this app, could you let me know if this issue still persists? Keep in mind that the WeMo Insight plugs only update their usage data when the device connected is turned on.

The amount of power it uses whilst waiting for commands without the device connected being on is never reported.
