### ISSUE TITLE
switching in flow not possible

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.wemo#2]
I created a flow which uses my wemo as a trigger (When "turned on" say "hello"). The flow works when testing on the flowinterface, it also works when the switch is triggered from the "devices" page. But by using the Wemo-android-app and the button on the Wemo nothing happens....

**Comment by freekwebdesign** [comment]
@bvdbos thanks for reporting this issue.
The Homey app does not actively poll if an external app switches the socket.
I will try to include this feature as well in the next update of the app.
If the new version is ready I will let you know.
