### ISSUE TITLE
Insight stops sending data

### ISSUE THREAD

**Issue by Swiftnesses** [athombv/com.wemo#4]
I'm facing an issue whereby the insight plug stops updating after some time. It's possible the app doesn't reconnect if a connection to the plug is lost (wifi disconnect etc)

**Comment by BasKiers** [comment]
Hi,

I've just released v1.1.11 in the appstore which I hope will improve the stability of the connection. Could you verify that you are still experiencing this problem with the latest version?

Regards,
Bas

**Comment by Swiftnesses** [comment]
This is still happening @BasKiers

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2598
