### ISSUE TITLE
Maker support 

### ISSUE THREAD

**Issue by Radiotechniman** [athombv/com.wemo#8]
please

**Comment by MatthewWaanders** [comment]
Hey @Radiotechniman,

As this app was due for a rewrite we looked into supporting this device. However we found out that this device doesn't add many new functionalities that Homey does not already have.

Could you give us your motivations for supporting this device?

**Comment by Radiotechniman** [comment]
Sorry I cannot, I sold the device some time ago

Regards,
Niels



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

2018-02-26 14:55 GMT+01:00 Matthew Waanders <notifications@github.com>:

**Comment by hachirotahoshino** [comment]
hi, personally i am interested in Maker support, i use maker to open my Flat ground floor door by shorting the open command on the interphone via wemo maker. I would really appreciate to be able to command it from homey and then from homekit. thanks
